export default function Profile() {
    return(
        <>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
            <p>teste</p>
        </>
    )
}